// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIoTWW5xnV2e-vHXD_cSC23OsIljJ8cU',
    appId: '1:112960083706:web:fd2b9af95560d7da80db43',
    messagingSenderId: '112960083706',
    projectId: 'orderly-d4db0',
    authDomain: 'orderly-d4db0.firebaseapp.com',
    storageBucket: 'orderly-d4db0.appspot.com',
    measurementId: 'G-R1JXTXBC4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULHyAot_LJY6n4ZaPYnEpfGkskYd9fcQ',
    appId: '1:112960083706:android:4ed1680adb11017f80db43',
    messagingSenderId: '112960083706',
    projectId: 'orderly-d4db0',
    storageBucket: 'orderly-d4db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgtHEUY8y7STndjbNlJ30Szypy9HUzm0',
    appId: '1:112960083706:ios:9d427351d873ec1980db43',
    messagingSenderId: '112960083706',
    projectId: 'orderly-d4db0',
    storageBucket: 'orderly-d4db0.appspot.com',
    iosBundleId: 'com.example.orderly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgtHEUY8y7STndjbNlJ30Szypy9HUzm0',
    appId: '1:112960083706:ios:9d427351d873ec1980db43',
    messagingSenderId: '112960083706',
    projectId: 'orderly-d4db0',
    storageBucket: 'orderly-d4db0.appspot.com',
    iosBundleId: 'com.example.orderly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeIoTWW5xnV2e-vHXD_cSC23OsIljJ8cU',
    appId: '1:112960083706:web:1d737aef0c0973b580db43',
    messagingSenderId: '112960083706',
    projectId: 'orderly-d4db0',
    authDomain: 'orderly-d4db0.firebaseapp.com',
    storageBucket: 'orderly-d4db0.appspot.com',
    measurementId: 'G-CPDYTG2C79',
  );
}
