// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  const FirebaseOptions web = FirebaseOptions(
    apiKey:  'AIzaSyCcJDS-LLoVkWP6ETeX-tk5JdjZnY7NDTw',
    appId: '1:872844068102:web:516a10972c62cc01354a87',
    messagingSenderId: '872844068102',
    projectId: 'orderly-33eb6',
    authDomain: 'orderly-33eb6.firebaseapp.com',
    storageBucket: 'orderly-33eb6.appspot.com',
    measurementId: 'G-76FJT5XZE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREesiD-VOGaUe66g6y1amNCM_evSe-AQ',
    appId: '1:872844068102:android:d6d9210452d278a0354a87',
    messagingSenderId: '872844068102',
    projectId: 'orderly-33eb6',
    storageBucket: 'orderly-33eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-UQVqHW5lX76NS94Pgh11BXmJi85kgQg',
    appId: '1:872844068102:ios:1d1f1644a6d2e412354a87',
    messagingSenderId: '872844068102',
    projectId: 'orderly-33eb6',
    storageBucket: 'orderly-33eb6.appspot.com',
    iosBundleId: 'com.example.orderly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-UQVqHW5lX76NS94Pgh11BXmJi85kgQg',
    appId: '1:872844068102:ios:414bdca430d6942f354a87',
    messagingSenderId: '872844068102',
    projectId: 'orderly-33eb6',
    storageBucket: 'orderly-33eb6.appspot.com',
    iosBundleId: 'com.example.orderly.RunnerTests',
  );
}
